export const customPageData = {
  Home: {
    digitalItServices: {
      services: [
        {
          icon: "Icon-ApplicationDevelopment",
          title: "Application Development",
        },
        {
          icon: "Icon-BigData&Analytics",
          title: "Big Data & Analytics",
        },
        {
          icon: "Icon-CloudServices&Solutions",
          title: "Cloud Services & Solutions",
        },
        {
          icon: "Icon-ManagedHyperscaleService",
          title: "Managed Hyperscale Service",
        },
        {
          icon: "Icon-Mainframe",
          title: "Mainframe",
        },
        {
          icon: "Icon-ManagedHosting",
          title: "Managed Hosting",
        },
      ],
    },
    digitalCXM: {
      services: [
        {
          icon: "Icon-RPA",
          title: "Robotic Process Automation (RPA) and RPAaS",
        },
        {
          icon: "Icon-Nounbot",
          title: "Bots (iTIA)",
        },
        {
          icon: "Icon-CloudServices&Solutions",
          title: "Cloud Contact Center as a Service (CCaaS)",
        },
      ],
    },
  },
  dashboard: {
    services: [
      {
        icon: "Icon-ReportAnIssue",
        title: "Report an Issue",
        text: "How can we help you resolve an issue?",
        link: "/coming-soon",
        linkText: "Report New",
      },

      {
        icon: "Icon-CreateRequest",
        title: "Create Request",
        text: "Browse our catalogue and request services, hardware or software",
        link: "/coming-soon",
        linkText: "Create New",
      },
      {
        icon: "Icon-KnowledgeBase",
        title: "Knowledge Base",
        text: "Search or browse our articles for devices & service-specific topics",
        link: "/coming-soon",
        linkText: "Learn more",
      },
      {
        icon: "Icon-GlobalIncidents",
        title: "Global Incidents",
        text: "Brows P1 and P2 incidents across the globe",
        link: "/coming-soon",
        linkText: "Browse",
      },
      {
        icon: "Icon-Quick-links",
        title: "Quick Links",
        link: "/coming-soon",
        link2: "/coming-soon",
        linkText: "Workday",
        linkText2: "How-to-knowledge-base",
      },
    ],
  },

  navbar_header: {
    navbar_header_link: {
      data: [
        {
          title: "Personal",
          isDropdown: false,
          href: "/personal",
          dropdownData: [],
        },
        {
          title: "Personal business",
          isDropdown: false,
          href: "/personal",
          dropdownData: [],
        },
        {
          title: "Business",
          isDropdown: true,
          href: "/business",
          dropdownData: [
            {
              title: "Personal",
              isDropdown: false,
              href: "/business/personal1",
              dropdownData: [],
            },
            {
              title: "Personal",
              isDropdown: false,
              href: "/business/personal2",
              dropdownData: [],
            },
          ],
        },
        {
          title: "Health",
          isDropdown: true,
          href: "/health",
          dropdownData: [
            {
              title: "Personal",
              isDropdown: false,
              href: "/health/personal1",
              dropdownData: [],
            },
            {
              title: "Personal",
              isDropdown: false,
              href: "/health/personal2",
              dropdownData: [],
            },
          ],
        },
        {
          title: "Agriculture",
          isDropdown: false,
          href: "/agriculture",
          dropdownData: [],
        },
        {
          title: "Social Impact",
          isDropdown: false,
          href: "/social-impact",
          dropdownData: [],
        },
      ],
    },
    navbar_header_option: {
      data: [
        {
          name: "search",
          title: "",
          icon: "Icon-Search",
          input: "text",
          isDropdown: false,
        },
        {
          name: "help",
          title: "Help",
          icon: "Icon-Help",
          input: "link",
          isDropdown: false,
        },
        {
          // name: "notification",
          // title: "",
          // icon: "Icon-Notification",
          // input: "dropdown",
          // isDropdown: false,
          isNotify: true
        },
        {
          name: "profile",
          title: "",
          icon: "Icon-Profile",
          input: "dropdown",
          dropDownIcon: "Icon-Dropdownwhite",
          isDropdown: true,
        },
      ],
    },
    navbar_header_region: {
      data: [],
    },
  },
  sidebar: [
    {  
      icon: "Icon-Home",
      title: "Home",
      link: "/",
      className: "svg-inverted",
      activeClassName: "svg-white",
      isAccordion: false,
    },
    {
      icon: "Icon-DigitalITServices",
      title: "Digital IT Services",
      link: "/digital-it-services",
      className: "svg-inverted",
      activeClassName: "svg-white",
      isAccordion: true,
    },
    {
      icon: "Icon-DigitalCXM",
      title: "Digital CXM",
      link: "/digital-cxm",
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "Icon-ServiceRequest",
      title: "Service Request",
      link: "/service-request",
      className: "svg-inverted ",
      activeClassName: "svg-white",
      isAccordion: true,
      drop:[
        {
            icon: "",
            title: "Email ",
            link: "/service-request/catalogue/2", 
            count: 4,
            className: "svg-inverted ",
            activeClassName: "svg-white ",
            isAccordion: false,
        },
        {
          icon: "",
          title: "Hardware ",
          link: "/service-request/catalogue/3", 
          count: 19,
          className: "svg-inverted mg10  ",
          activeClassName: "svg-white mg10 ",
          isAccordion: false,
        },
        {
          icon: "",
          title: "Internet / Client Application access",
          link: "/service-request/catalogue/4", 
          count: 1,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: false,
        },
        {
          icon: "",
          title: "LAN Connectivity ",
          link: "/service-request/catalogue/5", 
          count: 2,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: false,
        },
        {
          icon: "",
          title: "Network",
          link: "/service-request/catalogue/6", 
          count: 2,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: false,
        },
        {
          icon: "",
          title: "Other Services",
          link: "/service-request/catalogue/7",
          count: 10,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: false,
        },
        {
            icon: "",
            title: "My Cases",
            link: "#",
            // count: '',
            className: "svg-inverted mg10",
            activeClassName: "svg-white mg10",
            isAccordion: false,
          },
          {
            icon: "",
            title: "Knowledge Base",
            link: "#",
            // count: '',
            className: "svg-inverted",
            activeClassName: "svg-white ",
            isAccordion: false,
          },
          {
            icon: "",
            title: "Global Incident",
            link: "#",
            // count: '',
            className: "svg-inverted mg10",
            activeClassName: "svg-white mg10",
            isAccordion: false,
          },
          {
            icon: "",
            title: "Quick Links",
            link: "#",
            // count: '',
            className: "svg-inverted mg10",
            activeClassName: "svg-white mg10",
            isAccordion: true,
          }
      ]
    },
  ],
};

export const customCategoriesData = {








  sidebar: [
    {
      icon: "",
      title: "Access Request",
      link: "/service-request/catalogue/1",
      count: 13,
      className: "svg-inverted",
      activeClassName: "svg-white",
      isAccordion: true,
    },
    {
        icon: "",
        title: "Email ",
        link: "/service-request/catalogue/2",
        count: 4,
        className: "svg-inverted",
        activeClassName: "svg-white",
        isAccordion: true,
    },
    {
      icon: "",
      title: "Hardware ",
      link: "/service-request/catalogue/3",
      count: 19,
      className: "svg-inverted",
      activeClassName: "svg-white",
      isAccordion: true,
    },
    {
      icon: "",
      title: "Internet / Client Application access",
      link: "/service-request/catalogue/4",
      count: 1,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "",
      title: "LAN Connectivity ",
      link: "/service-request/catalogue/5",
      count: 2,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "",
      title: "Network",
      link: "/service-request/catalogue/6",
      count: 2,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "",
      title: "Other Services",
      link: "/service-request/catalogue/7",
      count: 10,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "",
      title: "SaaS Internal Requests ",
      link: "/service-request/catalogue/8",
      count: 3,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
    {
      icon: "",
      title: "Security",
      link: "/service-request/catalogue/9",
      count: 2,
      className: "svg-inverted mg10",
      activeClassName: "svg-white mg10",
      isAccordion: true,
    },
   
  ],
  showSidebar:[
    {
        icon: "",
        title: "ServiceNow",
        link: "/service-request/catalogue/10",
        count: 6,
        className: "svg-inverted mg10",
        activeClassName: "svg-white mg10",
        isAccordion: true,
      },
      {
        icon: "",
        title: "ServiceNow (External requests) ",
        link: "/service-request/catalogue/11",
        count: 6,
        className: "svg-inverted mg10",
        activeClassName: "svg-white mg10",
        isAccordion: true,
      },
      {
        icon: "",
        title: "Site Support ",
        link: "/service-request/catalogue/12",
        count: 4,
        className: "svg-inverted mg10",
        activeClassName: "svg-white mg10",
        isAccordion: true,
      },
      {
          icon: "",
          title: "Software & Applications",
          link: "/service-request/catalogue/13",
          count: 9,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " Solarwinds ",
          link: "/service-request/catalogue/14",
          count: 8,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " Special Access",
          link: "/service-request/catalogue/15",
          count: 2,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " Systems ",
          link: "/service-request/catalogue/16",
          count: 11,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: "TC3 ",
          link: "/service-request/catalogue/17",
          count: 2,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: "Telephony ",
          link: "/service-request/catalogue/18",
          count: 12,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: "Telephony/ Verint ",
          link: "/service-request/catalogue/19",
          count: 5,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " TIDS Internal Service Request ",
          link: "/service-request/catalogue/20",
          count: 12,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " Workday Support ",
          link: "/service-request/catalogue/21",
          count: 1,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
        },
        {
          icon: "",
          title: " Incident - Technical Support ",
          link: "/service-request/catalogue/22",
          count: 1,
          className: "svg-inverted mg10",
          activeClassName: "svg-white mg10",
          isAccordion: true,
      },
  ]
};

